In [2]:
import numpy as np
my_list = [1, 2, 3]
np.array(my_list)

array([1, 2, 3])

In [3]:
my_list

[1, 2, 3]

In [4]:
myarr = np.array(my_list)
myarr

array([1, 2, 3])

In [5]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
type(np.array(my_matrix))

numpy.ndarray

In [8]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones(5, dtype = int)

array([1, 1, 1, 1, 1])

In [17]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [19]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.linspace(20, 50, 6)

array([20., 26., 32., 38., 44., 50.])

In [22]:
np.linspace(20, 50, 6, dtype=int) # Dividing last value as linear space

array([20, 26, 32, 38, 44, 50])

In [23]:
np.eye(5) # identify matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])