In [1]:
import numpy as np
my_list = [1, 2, 3]
np.array(my_list)

array([1, 2, 3])

In [3]:
my_list

[1, 2, 3]

In [4]:
myarr = np.array(my_list)
myarr

array([1, 2, 3])

In [5]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
type(np.array(my_matrix))

numpy.ndarray

In [8]:
np.arange(0, 10) # Last value not include

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

In [2]:
np.zeros(5, dtype = float)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones(5, dtype = int)

array([1, 1, 1, 1, 1])

In [17]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [19]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.linspace(20, 50, 6)

array([20., 26., 32., 38., 44., 50.])

In [22]:
np.linspace(20, 50, 6, dtype=int) # Dividing last value as linear space

array([20, 26, 32, 38, 44, 50])

In [23]:
np.eye(5) # identify matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [2]:
np.random.rand(1)

array([0.18145103])

In [3]:
np.random.rand(2,3)

array([[0.97438674, 0.68283259, 0.95656574],
       [0.57317488, 0.91983647, 0.7319139 ]])

In [4]:
np.random.randn(10)

array([ 0.39649323, -0.99165588,  1.07984008, -0.63453309, -0.58171075,
       -1.23883096,  0.48429854,  0.74690717, -0.30627819,  1.80725235])

In [7]:
np.random.randn(2,4)

array([[ 0.40707378, -1.7945704 ,  1.1781971 ,  0.33671169],
       [-0.20125784, -1.7756071 , -1.16286557, -0.83089105]])

In [8]:
np.random.randint(0, 101, 10)

array([ 41,  14,  93, 100,   0,  37,  89,  94,  10,  38])

In [9]:
np.random.randint(50, 101, 10)

array([52, 50, 94, 88, 55, 64, 56, 66, 86, 74])

In [10]:
np.random.randint(0, 101, (4,5))

array([[  4, 100,  13,  57,  61],
       [ 38,  29,  18,  70,  34],
       [ 86,   0,  43,   1,  22],
       [ 45,  37,  84,  26,  45]])

In [11]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [12]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [13]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [14]:
np.random.rand(4)

array([0.68527698, 0.83389686, 0.30696622, 0.89361308])

In [15]:
np.random.rand(4)

array([0.72154386, 0.18993895, 0.55422759, 0.35213195])

In [16]:
arr = np.arange(0,25)

In [19]:
arr.shape

(25,)

In [17]:
arr.reshape(4,5)

ValueError: cannot reshape array of size 25 into shape (4,5)

In [18]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
ranarr = np.random.randint(0,101,10)

In [21]:
ranarr.max()

83

In [22]:
ranarr.min()

8

In [23]:
ranarr.argmax() # Show max value location

1

In [25]:
ranarr.argmin() # Show min value location

2

In [26]:
ranarr.dtype

dtype('int32')

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
arr.shape

(25,)

In [29]:
arr = arr.reshape(5,5)

In [30]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])