In [5]:
import numpy as np

In [6]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0,11)

In [13]:
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
slice_of_arr[:] = 99

In [16]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [17]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [18]:
arr_copy = arr.copy()

In [19]:
arr_copy[:] = 100

In [20]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [21]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [8]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [9]:
arr_2d.shape

(3, 3)

In [10]:
arr_2d[2]

array([35, 40, 45])

In [11]:
arr_2d[1][1]

25

In [12]:
arr_2d[0,2]

15

In [13]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [14]:
arr_2d[:2,1]

array([10, 25])

In [15]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [16]:
arr = np.arange(1,11)

In [17]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [20]:
bool_arr = arr>4

In [21]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [22]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [23]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [30]:
import numpy as np
import collections as cl
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

total_rolls_over_two = cl.Counter(dice_rolls>2)
total_rolls_over_two


Counter({True: 19, False: 10})

In [32]:
# Exercise Solution
import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

total_rolls_over_two = np.sum(dice_rolls>2)
total_rolls_over_two

19